# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-net

name: Build and Release

on:
  push:
    branches:
      - "main"
      - "release/*"

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Linux Checkout GIT
      uses: actions/checkout@v4
    - name: Linux Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Linux Build .NET
      run: dotnet publish ssh-agent-wsl-proxy -r linux-x64 -c Release -o Publish/linux-x64 /property:PublishAot=true
    - name: Linux Upload
      uses: actions/upload-artifact@v4
      with:
        name: ssh-agent-wsl-proxy-linux-x64
        path: Publish/**
  build-win-x64:
    runs-on: windows-latest
    steps:
    - name: Windows Checkout GIT
      uses: actions/checkout@v4
    - name: Windows Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Windows Build .NET
      run: dotnet publish ssh-agent-wsl-proxy -r win-x64 -c Release -o Publish/win-x64 /property:PublishAot=true
    - name: Windows Upload
      uses: actions/upload-artifact@v4
      with:
        name: ssh-agent-wsl-proxy-win-x64
        path: Publish/**
  release:
    if: ${{ startsWith(github.ref_name, 'release/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build-linux-x64, build-win-x64]
    steps:
    - name: Checkout GIT
      uses: actions/checkout@v4
    - name: Download
      uses: actions/download-artifact@v4
      with:
        pattern: ssh-agent-wsl-proxy-*
        path: Publish/ssh-agent-wsl-proxy
        merge-multiple: true
    - name: List
      run: find Publish/
    - name: Package
      run: |
        name=`basename $GITHUB_REF_NAME`
        tar -C Publish -zcf ssh-agent-wsl-proxy-$name.tar.gz ssh-agent-wsl-proxy/
    - name: Release
      run: |
        name=`basename $GITHUB_REF_NAME`
        gh release create "$name" --target "$GITHUB_REF_NAME" --draft --title "$name" 
        gh release upload "$name" ssh-agent-wsl-proxy-$name.tar.gz
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
