# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-net

name: Build and Test .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - "ssh-agent-wsl-proxy/**"
      - ".github/workflows/main.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ssh-agent-wsl-proxy/**"
      - ".github/workflows/main.yml"

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Linux Checkout GIT
      uses: actions/checkout@v4
    - name: Linux Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Linux Build .NET
      run: dotnet publish -r linux-x64 -c Release /property:PublishAot=true
    - name: Linux Upload
      uses: actions/upload-artifact@v4
      with:
        name: ssh-agent-wsl-proxy-linux-x64
        path: ssh-agent-wsl-proxy/bin/Release/net8.0/linux-x64/native/*
  build-win-x64:
    runs-on: windows-latest
    steps:
    - name: Windows Checkout GIT
      uses: actions/checkout@v4
    - name: Windows Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Windows Build .NET
      run: dotnet publish -r win-x64 -c Release /property:PublishAot=true
    - name: Windows Upload
      uses: actions/upload-artifact@v4
      with:
        name: ssh-agent-wsl-proxy-win-x64
        path: ssh-agent-wsl-proxy/bin/Release/net8.0/win-x64/native/*
  release:
    runs-on: ubuntu-latest
    needs: [build-linux-x64, build-win-x64]
    steps:
    - name: Download Windows
      uses: actions/download-artifact@v4
      with:
        pattern: ssh-agent-wsl-proxy-win-x64
    - name: Download Linux
      uses: actions/download-artifact@v4
      with:
        pattern: ssh-agent-wsl-proxy-linux-x64
    - name: List
      run: find .
